# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Sources/Declarator.h \
    ./Sources/Conf.h \
    ./Sources/Model/Model/Class.h \
    ./Sources/Model/Model/Components/CodeFunction.h \
    ./Sources/Model/Model/Components/Component.h \
    ./Sources/Model/Model/Components/Components.h \
    ./Sources/Model/Model/Components/Composition.h \
    ./Sources/Model/Model/Components/Link.h \
    ./Sources/Model/Model/Components/Process.h \
    ./Sources/Model/Model/Components/PureFunction.h \
    ./Sources/Model/Model/Components/Slot.hpp \
    ./Sources/Model/Model/Components/Variable.h \
    ./Sources/Model/Model/Model.h \
    ./Sources/Interface/Components/CompositionView.h \
    ./Sources/Interface/Components/ComponentView.h \
    ./Sources/Interface/Components/ComponentsView.h \
    ./Sources/Interface/Components/CodeFunctionView.h \
    ./Sources/Interface/Components/VariableView.h \
    ./Sources/Interface/ModelInterface.h \
    ./Sources/Interface/LibraryView/LibraryView.h \
    ./Sources/Model/Library/Library.h \
    ./Sources/Interface/SceneManager.h \
    ./Sources/Interface/SceneView.h \
    ./Sources/Interface/MainWindow.h \
    ./Sources/Interface/Components/LinkView.h \
    ./Sources/Interface/Components/ProcessView.h \
    ./Sources/Interface/Components/PureFunctionView.h \
    ./Sources/Interface/Components/SlotView.hpp
SOURCES += ./Sources/Interface/Components/VariableView.cpp \
    ./Sources/Interface/LibraryView/LibraryView.cpp \
    ./Sources/Main.cpp \
    ./Sources/Model/Model/Components/CodeFunction.cpp \
    ./Sources/Model/Model/Components/Component.cpp \
    ./Sources/Model/Model/Components/Components.cpp \
    ./Sources/Model/Model/Components/Composition.cpp \
    ./Sources/Model/Model/Components/Link.cpp \
    ./Sources/Model/Model/Components/Process.cpp \
    ./Sources/Model/Model/Components/PureFunction.cpp \
    ./Sources/Model/Model/Components/Variable.cpp \
    ./Sources/Model/Model/Model.cpp \
    ./Sources/Model/Library/Library.cpp \
    ./Sources/Interface/MainWindow.cpp \
    ./Sources/Interface/SceneManager.cpp \
    ./Sources/Interface/SceneView.cpp \
    ./Sources/Interface/Components/CompositionView.cpp \
    ./Sources/Interface/Components/ComponentView.cpp \
    ./Sources/Interface/Components/ComponentsView.cpp \
    ./Sources/Interface/Components/CodeFunctionView.cpp \
    ./Sources/Interface/Components/LinkView.cpp \
    ./Sources/Interface/Components/ProcessView.cpp \
    ./Sources/Interface/Components/PureFunctionView.cpp
FORMS += ./Sources/Interface/MainWindow.ui
RESOURCES += Sources/Modelia.qrc
